"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded package (three modules,
carried verbatim in dependency order), and the model pin/stage/verify cells are produced by the generator from
repository sources so they cannot drift from the package.

This template configures an E2E handwritten-line adaptation workflow for the ``<OCR>`` task: the pinned
florence-community/Florence-2-large snapshot is digest-verified and loaded, 800 MIT-licensed Belfort handwritten line
images with their transcripts are fetched as eight digest-pinned parquet row groups over HTTPS range requests, the
records are validated and split by line image, three capabilities (caption, detection, OCR) are run on a synthetic
drawing through the inference contract, the frozen model's character and word error rates over the held-out lines are
measured beside an empty-string and a constant-transcript baseline, a bounded fine-tuning of the last four decoder
layers runs on cached encoder outputs with validation-CER epoch selection, the held-out split is scored again, six
held-out lines and the three capabilities on the drawing are re-run with the adapted model, and the adapter is
exported and reloaded.

Review fixes (Notebook Review Framework v1, review PR #10, FL-M1..M3 / FL-m1..m5): the runtime is the fleet's uv
isolated environment (no in-kernel install, no restart); the guided layer (audience, task contract, how to use,
roadmap, predictions, worked answers, a change-one-thing activity, troubleshooting, glossary, conclusion) is added and
the setup cells are labelled Infrastructure; the split is described as what it is - a line-image split of one
collection with no page field - and Sections 4 and 8 report the transcripts repeated between splits and the held-out
rates without them; the transcript bound is no longer a second `MAX_TEXT_CHARS`; BYOD states and checks its real
minimum (12 distinct images), names the split it refuses, reports dropped duplicates, refuses duplicate file names,
takes a path as well as an upload and explains a cancelled upload; Section 8 reports a negative result instead of
asserting a positive one; the expected `<OD>` output and the run-to-run spread are stated; and Sections 5-7 start from
the pretrained model on every re-run, with the grounding experiment runnable as written.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "florence2_vision_language_pipeline",
    "repo_name": "florence2-vision-language-pipeline",
    "stem": "florence2_vision_language",
    "notebook_name": "florence2_vision_language_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "collapse_model_cell": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline / bioclip2-biodiversity-pipeline):
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml --python-version 3.12 --python-platform x86_64-manylinux_2_28 --generate-hashes
    # --only-binary :all: -o tutorials/requirements-colab.lock.txt`. The pins equal blip-captioning-pipeline's, so the
    # lock is that repository's (Colab T4 PASS at 2b8a77f), byte for byte.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "pipeline_class": "Florence2Pipeline",
    "weights_key": "florence-2-large-community",
    "modules": ["pipeline.py", "metrics.py", "samples.py"],
    "runtime_imports": ["torch", "transformers", "PIL"],
    "title": "Florence-2-large — DIMER E2E handwritten-line OCR adaptation tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/florence2-vision-language-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/florence2-vision-language-pipeline/blob/main/tutorials/florence2_vision_language_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-florence--community%2FFlorence--2--large-ffcc4d?style=flat",
            "https://huggingface.co/florence-community/Florence-2-large",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-microsoft%2FFlorence--2--large-181717?style=flat&logo=huggingface&logoColor=white",
            "https://huggingface.co/microsoft/Florence-2-large",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2311.06242-b31b1b.svg", "https://arxiv.org/abs/2311.06242"),
    ],
    "capability": "prompt-selected vision-language tasks (caption, detection and OCR demonstrated) and bounded supervised fine-tuning of the `<OCR>` task's last decoder layers on transcribed text lines, using the pinned Florence-2-large weights",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the "
        "pinned `florence-community/Florence-2-large` snapshot (a 1.54 GB `model.safetensors`; no pickle is opened anywhere), "
        "fetches the first eight row groups of the Belfort-line test shard from the Hugging Face Hub at an immutable revision "
        "with HTTPS range requests (about 44 MB; each row group refused on any SHA-256 or byte-total mismatch), validates the "
        "800 line records and splits them by line image into 600 / 60 / 140, runs three capabilities (`<CAPTION>`, `<OD>`, "
        "`<OCR>`) on a synthetic drawing through the inference contract with a combined input manifest and a rejection "
        "probe, measures the frozen model's `<OCR>` character and word error rates over the 140 held-out lines beside an "
        "empty-string and a constant-transcript baseline, runs a bounded fine-tuning of the last four BART decoder layers on "
        "cached encoder outputs with validation-CER epoch selection, scores the held-out lines again, re-runs six held-out "
        "lines and the three capabilities on the drawing with the adapted model, exports the adapter as safetensors with a "
        "manifest, and reloads that artifact into a fresh pipeline to verify transcript parity. The default path needs no "
        "repository clone, no DIMER worker or service, no credential, no upload dialog and no configuration edit "
        "(NOTEBOOK_SPEC 2.2 §5). A CUDA runtime is used automatically when present, and **a GPU runtime is required in "
        "practice**: on a Tesla T4 the model stages of the previous notebook version took about 20 minutes of cell time "
        "(six epochs 822 s, frozen scoring of 140 lines 90 s), while on CPU the beam-search decoding of some 800 lines plus "
        "600 cached forwards of a 777M-parameter model take hours. Building the isolated environment comes on top of this."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pretrained model first, so "
        "the earlier adaptation never carries over into a *frozen* number). Supply one zip through the upload dialog on "
        "Colab, or a zip or folder path in `BYOD_PATH` on any runtime. It holds line images plus a `transcripts.csv` "
        "(`file`, `text`, optional `id`; one row per image). The archive is read without its folders, so every file name "
        "must be unique. It needs **at least 12 distinct images**: the seeded split keeps 20 % for test and 15 % for "
        "validation and must leave at least 8 training, 2 validation and 2 test lines; Section 4 checks this before any "
        "model runs, names the split it refuses, and reports any pixel-duplicate images it drops. The records pass through "
        "the same validation, image-disjoint split, baselines, fine-tuning, held-out evaluation, artifact export and "
        "reload-parity cells as the Belfort sample; a result where the adapted model does not beat the frozen one is "
        "reported, not treated as an error. Uploaded files stay inside this runtime. BYOD is optional and never part of the "
        "default path."
    ),
    "intro": (
        "Florence-2 is one sequence-to-sequence model whose behaviour is selected by a **task prompt token**: the image is "
        "resized to 768 × 768 by the processor (aspect ratio is not preserved), encoded by a DaViT vision tower into 577 "
        "visual tokens that a BART encoder reads together with the prompt, and a 12-layer BART decoder generates text that "
        "the processor parses per task — plain text for captions and OCR, boxes plus labels in input-pixel coordinates for "
        "region tasks (776,505,344 parameters in all, published under the **MIT** licence). Decoding is **deterministic "
        "beam search** (`num_beams` = 3 from the snapshot generation config, `do_sample=False`). The output carries **no "
        "score**: captions and transcripts are plain generated text, boxes have no confidence.\n\n"
        "What this notebook adds to inference is **adaptation of one task on transcribed lines**. Florence-2's `<OCR>` was "
        "trained on printed and scene text; nineteenth-century French council minutes in cursive handwriting — the "
        "Belfort-line dataset — are far outside that distribution, and on them the frozen model reads nothing: it emits a "
        "dash or an empty string for almost every line, a character error rate of **0.992** on the 140 held-out "
        "lines (the build record's Tesla T4 figure), the empty baseline's 1.0 in all but name. So the honest question is "
        "narrow: does a bounded fine-tuning of the last four decoder layers on 600 transcribed lines move the held-out "
        "**CER** and **WER** on a held-out split of line images past two **non-adapted baselines** and the frozen model — "
        "and what does it do to the other tasks the same decoder serves? Nothing here is a claim about your documents or "
        "your script: it is one seeded split of one small labelled set, and the split is by line image, not by page "
        "(Section 4 explains why that matters).\n\n"
        "**Snapshot note:** the pin is the community \"official transformers converted checkpoint\" "
        "(`florence-community/Florence-2-large`), loadable by native `transformers` classes with `trust_remote_code=False`; "
        "the original `microsoft/Florence-2-large` snapshot needs remote code and was rejected (see the weight provenance "
        "document). The pinned revision ships `model.safetensors` (a 12-file manifest with the tokenizer files) — no pickle "
        "is opened anywhere in this notebook. Section 3 stages and digest-verifies those files before the processor or the "
        "model is constructed, and the loader refuses a checkpoint whose weights do not map cleanly onto the native "
        "architecture. The pipeline loads the checkpoint in **float32 on every device**: the adapter is trained in float32 "
        "and overlays without a cast, and CPU, Tesla-class and consumer GPUs then run the same arithmetic.\n\n"
        "**Who this is for.** A learner who knows basic Python and PIL and has met the idea of an encoder–decoder model, and "
        "wants to see how a pretrained document model is measured on labelled handwriting and adapted to it. No prior "
        "experience with Florence-2, OCR metrics or fine-tuning is assumed; each term is explained where it is first used "
        "and again in the **Glossary** at the end. A **GPU runtime** (for example a Colab or Kaggle T4) is needed in practice "
        "(Prerequisites).\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Inference | Fine-tuning |\n"
        "|---|---|---|\n"
        "| Input | one image (1 to 16,384 px a side) and a task prompt token such as `<OCR>`; `<CAPTION_TO_PHRASE_GROUNDING>` also takes a `text_input` | 600 training line images, each with its transcript as the target text |\n"
        "| Model | Florence-2-large: DaViT vision tower → BART encoder over 577 visual tokens + the prompt → 12-layer BART decoder, 3-beam search | the same model with the last 4 decoder layers and the decoder's embedding layer norm trained, everything else frozen |\n"
        "| Output | the task-parsed `result` (a caption or transcript string, or `{bboxes, labels}` in input pixels) and the raw generated text — no score | an adapter (safetensors) and held-out CER / WER / exact-match beside two baselines and the frozen model |\n\n"
        "**How to use this notebook.** Choose a GPU runtime, then **Runtime → Run all**. Sections 1–3 are **infrastructure** "
        "— the isolated environment, the carried code and the model verification — and can be run without study; their "
        "code is collapsed. The learning path starts in Section 4. Form fields (`# @param`) are the only values meant to be "
        "edited; the defaults reproduce the recorded path. Each stage asks you to **predict** before it runs, and the next "
        "cell opens with **What to notice** and a collapsible **Check your reasoning** block with a worked answer from the "
        "recorded Tesla T4 run of the previous notebook version (same model stages; your GPU's numbers can differ in the "
        "second or third decimal). Each optional experiment names the cell to change and the cells to re-run. Section 10 is "
        "a **change-one-thing activity**. **Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. "
        "Your notes are optional and are not required submissions.\n\n"
        "**Roadmap:** 4 fetch, validate and split the lines → 5 three capabilities on a drawing with the pretrained model → "
        "6 two baselines and the pretrained model on the test lines → 7 fine-tune the last decoder layers → 8 compare on the "
        "held-out lines → 9 look at the lines, re-run the capabilities, export and reload → 10 **change one thing: a higher "
        "learning rate** → conclude. Core concepts are Sections 5 and 6 (what the model emits and how it is scored); "
        "evaluation practice is Sections 4, 7 and 8 (split, selection, held-out comparison); engineering and "
        "reproducibility are Sections 1–3 and 9."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *image + task token → encoder → decoder → task-parsed text or boxes* "
        "and say why none of the outputs carries a score (Section 5); (2) read corpus CER and WER against an empty and a "
        "constant-transcript baseline, and say why a rate above 1.0 means the model is generating rather than reading "
        "(Section 6); (3) explain how the validation split, never the test split, chooses the kept epoch (Section 7); (4) "
        "predict and then check how CER, WER and hypothesis length move after a bounded fine-tuning, and say why CER can fall "
        "while WER does not (Section 8); (5) say what a line-image split does and does not protect against when the data has "
        "no page field (Sections 4 and 8); (6) check that an exported adapter reproduces the evaluated model (reload parity, "
        "Section 9); and (7) predict and then observe what a higher learning rate changes (Section 10)."
    ),
    "exclusions": (
        "the other task tokens in `TASKS` are exposed but not demonstrated by default — `<DETAILED_CAPTION>`, "
        "`<MORE_DETAILED_CAPTION>`, `<DENSE_REGION_CAPTION>`, `<REGION_PROPOSAL>`, `<OCR_WITH_REGION>` and "
        "`<CAPTION_TO_PHRASE_GROUNDING>` (the only task that takes a `text_input`; an optional experiment runs it); "
        "segmentation of any kind, open-vocabulary detection, visual question answering, confidence scores for boxes or "
        "text, fine-tuning of the vision tower, the projector, the encoder, the embeddings or the first eight decoder layers, "
        "fine-tuning of any task but `<OCR>`, evaluation on an OCR benchmark proper (only one seeded 800-line sample is "
        "scored here), a page- or writer-disjoint split (the dataset carries no page or writer field), and any claim that "
        "French cursive minutes stand in for your documents. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and PIL, and Colab or Jupyter familiarity; what a sequence-to-sequence model's task prompt and generated tokens are; what a bounding box in pixel coordinates is. No prior experience with Florence-2, OCR metrics or fine-tuning: the notebook explains task tokens, beam search, CER and WER, the medoid baseline, the frozen encoder cache, teacher forcing and validation-based epoch selection where they are first used, and the Glossary repeats them.",
        "- **Runtime:** a fresh **Linux x86_64** runtime with a CUDA GPU — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own Python 3.12.12 environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter, and a Windows or macOS kernel is not supported (Section 1 stops with that message). Generation is batched for the corpus stages — every `<OCR>` prompt is the same 587 tokens (577 image tokens plus the task token), so a batch needs no padding — and the build record measured 90 s to score 140 lines with 3-beam search and 822 s for the six epochs (caching the encoder outputs for 600 lines took 371 s) on a Tesla T4, about 20 minutes of cell time for the model stages; a CPU runtime would take hours. The locked install (PyTorch 2.14.0 with its CUDA libraries, a few GB) and the 1.54 GB checkpoint are the large downloads of the run; the row groups are about 44 MB.",
        "- **Data contract:** records are `{id, image, text}` — `image` a PIL image (or a file decodable by Pillow) with sides within 1..16,384 px and at most 4096² pixels, `text` its transcript (1..`MAX_TRANSCRIPT_CHARS` = 512 characters after whitespace runs are collapsed; case and punctuation kept). Ids match `[A-Za-z0-9_.:-]{1,64}` and are unique; a training split needs 8..5,000 records. Splitting de-duplicates by decoded pixels so no image lands in two splits, and the seeded BYOD split (65 / 15 / 20 %) must leave at least 8 training, 2 validation and 2 test lines, so **a BYOD dataset needs at least 12 distinct images** (Section 4 checks it before any model runs and names the split it refuses).",
        "- **BYOD layout:** one zip (by upload on Colab, or by path in `BYOD_PATH` on any runtime; a folder path also works) holding the line images and a `transcripts.csv` with the columns `file` and `text` (optional `id`). The archive is read without its folders, so every file name must be unique; two files with one name are refused with a message saying so.",
        "- **Validation is structural, not semantic:** every image is decoded and every transcript checked for length, but nothing checks that a transcript says what its image shows — a mislabelled set is fine-tuned on without complaint.",
        "- **Expected output:** a \"slow image processor\" notice from `transformers` is expected and harmless. A `RuntimeError: checkpoint does not match the native Florence-2 architecture` means the staged weights are not the pinned converted checkpoint.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there. The default path uploads nothing.",
        "- **External access (data):** besides the model snapshot, the default path reads eight row groups of `default/test/0000.parquet` from `https://huggingface.co/datasets/Teklia/Belfort-line/resolve/<revision>/` at the immutable parquet-conversion revision `c4a74bbd…` with HTTPS range requests (the parquet footer plus about 44 MB of row-group bytes out of a 210 MB shard), each row group pinned by SHA-256 and byte total in the carried `samples.py` and refused on any mismatch. Belfort-line is published under the MIT licence (Teklia; Tarride et al. 2023); nothing is redistributed by this repository.",
    ],
    "cells": [
        {
            "md": (
                "## 4. Belfort lines, the transcripts and the split\n\n"
                "`fetch_corpus` returns the eight pinned row groups from the cache under `weights/belfort/` or the Hub at the "
                "pinned parquet-conversion revision — `pyarrow` reads the shard's footer and exactly those row groups over "
                "HTTPS range requests; every cached file is re-hashed and every fetched row group refused on any SHA-256 or "
                "byte-total mismatch — and `read_corpus` turns each row into a record: the line image (128 px tall, 145 to "
                "8,956 px wide) and its crowdsourced transcript with whitespace runs collapsed. `build_sample_dataset` draws a "
                "seeded split **by line image** (600 / 60 / 140). `validate_dataset` then checks every record against the "
                "contract, `check_split_disjoint` asserts no image (by decoded-pixel digest) is shared, and the training "
                "split's summary table is written to `outputs/{stem}_train.csv`.\n\n"
                "**What the split does and does not protect against.** No line image is in two splits. But the Belfort parquet "
                "has only two columns, `image` and `text` — no page, writer or register — so the split cannot keep a page's "
                "lines together: lines cut from one page can sit in training and in test, in the same hand. Nor would cutting "
                "the corpus into runs of consecutive lines help, because the shard is not in page order (neighbouring lines "
                "come from different years and registers: in the 800 lines, six of the eight pairs of year-bearing lines at "
                "most three rows apart name years more than two years apart, and the width of one line image predicts the "
                "next one's with a correlation of 0.02). The held-out rates in Section 8 are therefore a **same-collection "
                "estimate**: they measure lines from pages and hands the model may have trained on, and are likely optimistic "
                "for a new register or a new hand. A second, smaller overlap is textual: formulaic lines such as \"Le "
                "Conseil Municipal\" repeat across pages, so a few test transcripts also occur verbatim in training. The cell "
                "counts them (`transcript_overlap`), and Section 8 reports the rates with and without those lines.\n\n"
                "**Bring your own data:** set `USE_BYOD = True`, either leave `BYOD_PATH` empty to get an upload dialog "
                "(Colab only) or set it to a zip or folder already in this runtime, then select this cell and choose **Runtime → "
                "Run after**. An empty or cancelled upload, a runtime without the Colab upload dialog and no `BYOD_PATH`, or a "
                "path that does not exist stops with a message saying what to supply. `load_byod_dataset` refuses two files "
                "with one name (the archive is read without its folders), a missing `transcripts.csv`, an image without a row "
                "or a row without an image; pixel-duplicate images are counted and named before the split drops them; and "
                "`split_dataset` refuses a dataset that leaves fewer than 8 training, 2 validation or 2 test lines, naming the "
                "split (at least 12 distinct images). Under BYOD the printed provenance and `result.json` describe your "
                "upload, not the Belfort corpus.\n\n"
                "Look for: 800 lines and 33,117 reference characters, three digests, the number of validation and test "
                "transcripts that also occur in training, and four refusal probes — a duplicate id, an empty transcript, an "
                "image above the side ceiling, and a dataset too small to use — each rejected before the model does anything.\n\n"
                "**Predict before running:** of the 140 test lines, how many do you expect to have a transcript that also "
                "appears, word for word, among the 600 training lines — none, a handful, or dozens?"
            ),
            "code": (
                "import hashlib\n"
                "import json\n"
                "import time\n\n"
                "import numpy as np\n"
                "from PIL import Image, ImageDraw, ImageFont\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "byod = None\n"
                "if USE_BYOD:\n"
                "    if BYOD_PATH.strip():\n"
                "        byod_source = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not byod_source.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} does not exist in this runtime: fix the path, or leave BYOD_PATH empty to upload a zip in Colab.')\n"
                "        file_name, payload = byod_source.name, (byod_source.read_bytes() if byod_source.is_file() else None)\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the zip (or folder) in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise ValueError(f'Upload exactly one .zip file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a zip or folder already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        byod_source = Path('work') / 'byod.zip'\n"
                "        byod_source.parent.mkdir(parents=True, exist_ok=True)\n"
                "        byod_source.write_bytes(payload)\n"
                "    records = load_byod_dataset(byod_source)\n"
                "    unique_records, dropped_duplicates = drop_duplicate_images(records)\n"
                "    print({{'byod_records': len(records), 'distinct_images': len(unique_records), 'pixel_duplicates_dropped': len(dropped_duplicates), 'dropped_ids': dropped_duplicates[:20], 'needed': f'at least {{byod_record_limits()[0]}} distinct images'}})\n"
                "    splits = split_dataset(unique_records, seed=SPLIT_SEED)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod': len(records), 'distinct_images': len(unique_records)}}\n"
                "    byod = {{'file': file_name, 'records': len(records), 'distinct_images': len(unique_records), 'duplicates_dropped': dropped_duplicates, 'zip_sha256': hashlib.sha256(payload).hexdigest() if payload is not None else None}}\n"
                "else:\n"
                "    t0 = time.perf_counter()\n"
                "    corpus_groups = fetch_corpus(cache_dir='weights/belfort')\n"
                "    corpus = read_corpus(corpus_groups)\n"
                "    splits = build_sample_dataset(corpus, seed=SPLIT_SEED)\n"
                "    data_source = f'{{CORPUS_NAME}} @ {{CORPUS_REVISION[:12]}} ({{CORPUS_LICENSE}})'\n"
                "    raw_rows = {{'row_groups': len(corpus_groups), 'lines': sum(len(v) for v in corpus_groups.values()), 'bytes': sum(len(r['image']) + len(r['text'].encode('utf-8')) for v in corpus_groups.values() for r in v), 'seconds': round(time.perf_counter() - t0, 1)}}\n"
                "dataset_manifests = {{name: validate_dataset(part, min_records=MIN_RECORDS if name == 'train' else 1) for name, part in splits.items()}}\n"
                "splits = {{name: manifest['records'] for name, manifest in dataset_manifests.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "write_dataset_csv(train_records, 'outputs/{stem}_train.csv')\n"
                "print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'split_unit': 'line image (no page or writer field)'}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'chars': manifest['text_chars'], 'words': manifest['text_words']['total'], 'width': manifest['image_width'], 'height': manifest['image_height'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "overlap = {{'validation': transcript_overlap(train_records, val_records), 'test': transcript_overlap(train_records, test_records)}}\n"
                "test_by_id = {{r['id']: r for r in test_records}}\n"
                "print({{'transcripts_also_in_train': {{name: len(ids) for name, ids in overlap.items()}}, 'test_examples': [test_by_id[i]['text'] for i in overlap['test'][:5]]}})\n"
                "example = train_records[0]\n"
                "example['image'].save('outputs/{stem}_example_line.png')\n"
                "print({{'example': {{'id': example['id'], 'image': list(example['image'].size), 'text': example['text']}}}})\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in train_records[:8]],\n"
                "    'empty transcript': [{{**train_records[0], 'text': '   '}}, *train_records[1:8]],\n"
                "    'image above the side ceiling': [{{**train_records[0], 'image': Image.new('RGB', (MAX_IMAGE_SIDE + 1, 8))}}, *train_records[1:8]],\n"
                "    'too small': train_records[:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three split sizes, `split_unit`, the transcript-overlap counts with their examples, "
                "and four rejected probes.\n\n"
                "<details><summary>Check your reasoning</summary>A handful. With the default seed, 5 of the 140 test lines and "
                "2 of the 60 validation lines have a transcript that also occurs in training: formulaic lines (\"Le Conseil "
                "Municipal\", \"Après en avoir délibéré, à l'unanimité :\") and bare numbers (\"100\", \"440\"). They are 84 of "
                "the 6,169 reference characters of the test split, so they cannot move the corpus CER much, and Section 8 shows "
                "the rates without them. The larger, unmeasurable overlap is the one the dataset cannot show: lines of the "
                "same page and hand on both sides of the split.</details>\n\n"
                "## 5. Run three capabilities on a synthetic drawing through the inference contract\n\n"
                "The inference contract is exercised as the multi-capability tutorial exercised it: a 512 × 512 white canvas "
                "drawn in code — a filled red square, a filled blue circle and the text `DIMER 2026` in Pillow's bundled font "
                "— whose drawn text is the **known OCR reference**; a different image family from the handwritten lines, and "
                "a drawing the adapted model will see again in Section 9. `validate_inputs` applies exactly the checks `run` "
                "applies (image sides `MIN_IMAGE_SIDE`..`MAX_IMAGE_SIDE` and at most `MAX_IMAGE_PIXELS`, a task token inside "
                "`TASKS`, a `text_input` only for the tasks that take one, `max_new_tokens` in 1..`MAX_NEW_TOKENS`, a positive "
                "`num_beams`) and one combined manifest records the requests; an unsupported task token is validated too and "
                "its rejection recorded as a finding. Each entry of `CAPABILITIES` may carry a `text_input`, which is passed to "
                "`validate_inputs` and `run` (only `<CAPTION_TO_PHRASE_GROUNDING>` takes one). `run` returns the task-parsed "
                "`result` — a caption string, `{{bboxes, labels}}` in input pixels with **no confidence scores**, an OCR "
                "string — the raw `generated_text` and the generation settings; structural checks assert each output's "
                "contract. The per-image `evaluation_report` over the results scores OCR against the drawn text "
                "(`sample-sanity`) and reports the caption and the detections `not-measurable` — plumbing evidence, not a "
                "measurement; whether the model is *good at handwriting* is what Section 6 measures on 140 lines. The printed "
                "ceilings name both text bounds: `MAX_TEXT_CHARS` (1000) for a grounding `text_input` and "
                "`MAX_TRANSCRIPT_CHARS` (512) for a training transcript.\n\n"
                "**Every pass starts from the pretrained model.** Section 7 changes the model in memory. If this cell, Section 6 "
                "or Section 7 runs again after Section 7 (a BYOD run or one of the optional experiments), it first reloads the "
                "pretrained model from the verified snapshot with `reset_to_pretrained()`, so a *frozen* number is never read "
                "from the adapted model.\n\n"
                "**Predict before running:** the drawing holds a red square, a blue circle and two words. How many boxes will "
                "`<OD>` return, and what labels? Will `<OCR>` read `DIMER 2026` exactly?"
            ),
            "code": (
                "import gc\n\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pretrained model: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    if torch.cuda.is_available():\n"
                "        torch.cuda.empty_cache()\n"
                "    pipe = Florence2Pipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pretrained model, from the verified snapshot', 'reason': 'an earlier pass had adapted the model in memory'}})\n\n\n"
                "reset_to_pretrained()\n"
                "drawing = Image.new('RGB', (512, 512), (255, 255, 255))\n"
                "draw = ImageDraw.Draw(drawing)\n"
                "drawn_square = (64, 64, 224, 224)\n"
                "draw.rectangle(drawn_square, fill=(220, 30, 30))\n"
                "draw.ellipse((300, 96, 460, 256), fill=(30, 60, 220))\n"
                "drawing_reference = 'DIMER 2026'\n"
                "draw.text((96, 360), drawing_reference, fill=(0, 0, 0), font=ImageFont.load_default(size=48))\n"
                "drawing_name = 'synthetic_shapes_text_512'\n"
                "drawing_sha256 = hashlib.sha256(np.asarray(drawing).tobytes()).hexdigest()\n"
                "print({{'ceilings': {{'MIN_IMAGE_SIDE': MIN_IMAGE_SIDE, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'MAX_IMAGE_PIXELS': MAX_IMAGE_PIXELS, 'MAX_NEW_TOKENS': MAX_NEW_TOKENS, 'DEFAULT_MAX_NEW_TOKENS': DEFAULT_MAX_NEW_TOKENS, 'DEFAULT_LINE_MAX_NEW_TOKENS': DEFAULT_LINE_MAX_NEW_TOKENS, 'MAX_TEXT_CHARS (grounding text_input)': MAX_TEXT_CHARS, 'MAX_TRANSCRIPT_CHARS (training transcript)': MAX_TRANSCRIPT_CHARS, 'NUM_BEAMS': NUM_BEAMS, 'MIN_RECORDS': MIN_RECORDS, 'MAX_RECORDS': MAX_RECORDS, 'device': pipe.device, 'dtype': pipe.dtype}}}})\n"
                "print({{'TASKS_WITHOUT_TEXT': TASKS_WITHOUT_TEXT, 'TASKS_WITH_TEXT': TASKS_WITH_TEXT}})\n"
                "CAPABILITIES = {{\n"
                "    '<CAPTION>': {{'input': 'image only', 'output': 'result: str (one short caption); no score', 'max_new_tokens': 64}},\n"
                "    '<OD>': {{'input': 'image only', 'output': \"result: {{'bboxes': [[x1, y1, x2, y2], ...] in input pixels, 'labels': [str, ...]}}; no per-box score\", 'max_new_tokens': DEFAULT_MAX_NEW_TOKENS}},\n"
                "    '<OCR>': {{'input': 'image only', 'output': 'result: str (transcribed text, reading order chosen by the model); no score', 'max_new_tokens': DEFAULT_LINE_MAX_NEW_TOKENS}},\n"
                "}}\n"
                "manifests = {{task: validate_inputs(drawing, task, contract.get('text_input'), max_new_tokens=contract['max_new_tokens'], num_beams=NUM_BEAMS, names=[drawing_name]) for task, contract in CAPABILITIES.items()}}\n"
                "input_manifest = {{**manifests['<CAPTION>'], 'task': 'multi-capability: ' + ', '.join(CAPABILITIES), 'tasks': list(CAPABILITIES), 'findings': [], 'capabilities': manifests}}\n"
                "try:\n"
                "    validate_inputs(drawing, '<REFERRING_EXPRESSION_SEGMENTATION>')\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'unsupported-task-probe', 'task': '<REFERRING_EXPRESSION_SEGMENTATION>', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'drawing': drawing_name, 'sha256': drawing_sha256[:16] + '...', 'manifest_verdict': input_manifest['verdict'], 'findings': len(input_manifest['findings'])}})\n\n\n"
                "def run_capabilities(pipeline, label):\n"
                "    results, timings = {{}}, {{}}\n"
                "    for task, contract in CAPABILITIES.items():\n"
                "        started = time.perf_counter()\n"
                "        results[task] = pipeline.run(drawing, task, contract.get('text_input'), max_new_tokens=contract['max_new_tokens'], num_beams=NUM_BEAMS)\n"
                "        timings[task] = round(time.perf_counter() - started, 3)\n"
                "    caption, detections, ocr_text = results['<CAPTION>']['result'], results['<OD>']['result'], results['<OCR>']['result']\n"
                "    checks = {{\n"
                "        'caption_is_text': isinstance(caption, str),\n"
                "        'od_boxes_and_labels_aligned': isinstance(detections, dict) and len(detections.get('bboxes', [])) == len(detections.get('labels', [])),\n"
                "        'od_boxes_inside_image': all(0 <= x1 <= x2 <= drawing.width and 0 <= y1 <= y2 <= drawing.height for x1, y1, x2, y2 in detections.get('bboxes', [])),\n"
                "        'ocr_is_text': isinstance(ocr_text, str),\n"
                "        'deterministic_settings': all(r['generation']['do_sample'] is False and r['generation']['num_beams'] == NUM_BEAMS for r in results.values()),\n"
                "        'identity_reported': all(r['model_id'] == MODEL_ID and r['model_revision'] == MODEL_REVISION for r in results.values()),\n"
                "    }}\n"
                "    if not all(checks.values()):\n"
                "        raise RuntimeError(f'capability output failed a sanity check: {{checks}}')\n"
                "    report = evaluation_report(list(results.values()), drawing_reference, sample_kind='synthetic (drawn in this notebook)')\n"
                "    preview = drawing.copy()\n"
                "    marker = ImageDraw.Draw(preview)\n"
                "    for (x1, y1, x2, y2), name in zip(detections.get('bboxes', []), detections.get('labels', [])):\n"
                "        marker.rectangle((x1, y1, x2, y2), outline=(0, 160, 0), width=3)\n"
                "        marker.text((x1 + 4, y1 + 4), name, fill=(0, 160, 0))\n"
                "    preview.save(f'outputs/{stem}_preview_{{label}}.png')\n"
                "    extra = {{task: {{'text_input': CAPABILITIES[task].get('text_input'), 'result': r['result']}} for task, r in results.items() if task not in ('<CAPTION>', '<OD>', '<OCR>')}}\n"
                "    print({{label: {{'seconds': timings, 'checks': checks, 'caption': caption, 'detections': list(zip(detections.get('labels', []), [[round(v) for v in b] for b in detections.get('bboxes', [])])), 'ocr': ocr_text, 'ocr_cer': {{m['id']: round(m['value'], 4) for m in report['metrics']}}, 'verdict': report['verdict'], **({{'other_tasks': extra}} if extra else {{}})}}}})\n"
                "    return results, timings, checks, report\n\n\n"
                "frozen_results, frozen_timings, frozen_checks, frozen_report = run_capabilities(pipe, 'frozen')"
            ),
        },
        {
            "md": (
                "**What to notice:** the two text bounds in the ceilings, the three `checks`, the caption, the box list with "
                "its labels, the OCR string and its CER against the drawn text.\n\n"
                "<details><summary>Check your reasoning</summary>In the recorded Tesla T4 run of the previous notebook version "
                "(same model stages, float32) the frozen model captioned the drawing `a red and blue circle with the word dimer "
                "2026 on it`, returned **one** box covering the whole drawing (`[0, 0, 511, 511]`) labelled `poster` — not "
                "one box per shape — and read `DIMER 2026` exactly (CER 0.000). One box around everything is a legitimate "
                "`<OD>` answer for a poster-like image; nothing in the output tells you it is less useful than three boxes, "
                "because there is no score. Printed text in a clean font is what this model was trained on; the handwriting "
                "in Section 6 is not.</details>\n\n"
                "## 6. Baselines and the frozen model on the test lines\n\n"
                "Two non-adapted baselines frame the adaptation, each scored by `ocr_metrics` (carried in `metrics.py`): the "
                "**character error rate** and **word error rate** as micro averages — total Levenshtein edits over total "
                "reference characters or words, the corpus CER/WER of the handwriting-recognition literature — beside the "
                "macro (per-line mean) rates and the exact-match rate. Neither rate is capped: a hypothesis longer than its "
                "reference pushes the rate **above 1.0**, the signal that the model is generating text the line does not carry. "
                "The **empty-string** baseline predicts nothing and scores CER 1.0 exactly (every reference character is a "
                "deletion) — the floor any recogniser must beat to do better than silence. The **constant-transcript** baseline "
                "predicts one training transcript — the medoid, the line closest on average to the others — for every test "
                "line: what corpus statistics buy without reading the image. The **frozen model** is scored by `pipe.evaluate`, "
                "which runs `<OCR>` in batches of `EVAL_BATCH_SIZE` with `NUM_BEAMS` beams under a `LINE_MAX_NEW_TOKENS` "
                "budget and returns the hypotheses with the rates. The cell reloads the pretrained model first if an earlier "
                "pass adapted it, and refuses to report an adapted model as frozen; four hypotheses are printed under their "
                "references.\n\n"
                "**Predict before running:** the frozen model reads printed text well (Section 5). On cursive "
                "nineteenth-century French, will its CER land nearer the empty baseline's 1.0, or nearer 0? Will its "
                "hypotheses be shorter or longer than the references?"
            ),
            "code": (
                "METRICS = ('cer', 'wer', 'cer_macro', 'exact_match')\n"
                "LINE_MAX_NEW_TOKENS = 128  # @param {{type:\"integer\"}}\n\n"
                "reset_to_pretrained()\n"
                "baseline_empty = empty_baseline(test_records)\n"
                "baseline_constant = constant_baseline(train_records, test_records)\n"
                "print({{'empty_baseline': {{k: round(baseline_empty[k], 3) for k in METRICS}}, 'n': baseline_empty['n'], 'note': baseline_empty['baseline']}})\n"
                "print({{'constant_baseline': {{k: round(baseline_constant[k], 3) for k in METRICS}}, 'note': baseline_constant['baseline']}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records, max_new_tokens=LINE_MAX_NEW_TOKENS, num_beams=NUM_BEAMS, batch_size=EVAL_BATCH_SIZE)\n"
                "if frozen_test['adapted']:\n"
                "    raise RuntimeError('Section 6 must score the pretrained model, but the model in memory is adapted. Restart the session and choose Run all.')\n"
                "print({{'frozen_model_test': {{k: round(frozen_test[k], 3) for k in METRICS}}, 'n': frozen_test['n'], 'ref_chars': frozen_test['ref_chars'], 'hyp_chars': frozen_test['hyp_chars'], 'truncated': frozen_test['truncated'], 'verdict': frozen_test['verdict'], 'adapted': frozen_test['adapted'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'definitions': frozen_test['definitions']}})\n"
                "for record, hypothesis in zip(test_records[:4], frozen_test['hypotheses'][:4], strict=True):\n"
                "    print({{'id': record['id'], 'reference': record['text'], 'frozen': hypothesis[:120]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** `adapted: False`, the frozen CER beside the two baselines, `hyp_chars` against "
                "`ref_chars`, and the four printed hypotheses.\n\n"
                "<details><summary>Check your reasoning</summary>Nearer 1.0, and much shorter. In the recorded T4 run the "
                "empty baseline scored CER 1.000, the constant transcript 0.944 and the frozen model **0.992** — essentially "
                "silence: its hypotheses held about 0.04 times as many characters as the references (a dash or nothing for "
                "most lines). The constant transcript beats it because a guessed common line shares some characters with "
                "many references. A model that reads print perfectly can read nothing in a hand it never saw: that is the gap "
                "the fine-tuning in Section 7 tries to close.</details>\n\n"
                "## 7. Bounded fine-tuning of the last decoder layers\n\n"
                "`pipe.adapt` trains only the last four of the 12 BART decoder layers and the decoder's embedding layer norm — "
                "67,188,736 of 776,505,344 parameters — while the DaViT vision tower, the projector, the BART encoder, the "
                "shared embeddings (tied to the output head) and the first eight decoder layers stay frozen. Each training line "
                "is the `<OCR>` prompt with its 577 visual tokens on the encoder side and, on the decoder side, the transcript's "
                "tokens between the start and end tokens; the loss is the **sequence-to-sequence cross-entropy** over those "
                "target tokens, teacher-forced (the decoder is fed the correct previous tokens, not its own guesses) — the "
                "checkpoint's own training objective. Because everything before the decoder is frozen, the encoder output for "
                "every training line is computed once under no gradient and cached (the **frozen encoder cache**, 587 × 1024 "
                "numbers per line), and each step runs only the decoder on those cached states — the loss equals the full "
                "model's loss exactly, at a fraction of the cost. AdamW without weight decay at a fixed learning rate, gradient "
                "clipping at 1.0, seeded shuffling (seed 0, printed below), no scheduler, no augmentation. Epoch 0 records the "
                "frozen model's validation rates; every epoch is scored on the 60 validation lines with the same beam search, "
                "and the epoch with the **lowest validation CER** is kept — the test split plays no part in that choice. If no "
                "epoch beats the frozen model on validation, the selector keeps epoch 0 and that outcome is reported.\n\n"
                "**Adaptation always starts from the pretrained model.** If this cell runs again (for example with "
                "`LEARNING_RATE = 1e-4` in Section 10), it first reloads the pretrained model from the verified snapshot, so "
                "the new training never stacks on the previous one, epoch 0 really is the frozen model, and the exported "
                "adapter holds exactly what this run trained; `pipe.adapt` itself refuses a model that is already adapted.\n\n"
                "**Run-to-run spread.** Beam search is deterministic only for fixed weights, device and dtype, and GPU training "
                "is not bit-reproducible across GPU models or library builds: expect your epoch rates to differ from the "
                "recorded run in the second or third decimal (the release record treats a few hundredths as the expected "
                "spread), and the kept epoch to move by one when two epochs are that close.\n\n"
                "**Predict before running:** will the validation CER fall in every epoch? Will the training loss and the "
                "validation CER keep moving together?"
            ),
            "code": (
                "EPOCHS = 6  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 5e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 8  # @param {{type:\"integer\"}}\n\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row.update({{'val_' + k: round(entry['val'][k], 3) for k in METRICS}})\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, max_new_tokens=LINE_MAX_NEW_TOKENS, num_beams=NUM_BEAMS, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'task': adapt_result['task'], 'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'first_trainable_layer': adapt_result['first_trainable_layer'], 'learning_rate': adapt_result['lr'], 'seed': adapt_result['seed'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'selection_split': 'validation', 'loss': adapt_result['loss'], 'cache_seconds': adapt_result['cache_seconds'], 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled the frozen model, how the training loss and the validation CER move "
                "from epoch to epoch, and which epoch is kept.\n\n"
                "<details><summary>Check your reasoning</summary>No, and no. In the recorded T4 run the validation CER fell from "
                "0.969 (epoch 0, the frozen model; epoch 1 also 0.969) to 0.799 at epoch 6, but not in every epoch — 0.821 at "
                "epoch 2, then 0.852, 0.801, 0.808, 0.799 — while the training loss fell steadily from 6.63 (epoch 1) to 3.13. "
                "The validation curve flattened near 0.80 while the loss kept falling: the decoder fits the 600 training "
                "transcripts better than it learns to read. Four decoder layers move the model from silence to something "
                "that is not yet reading: the frozen encoder's representation of a 128-px cursive line squashed into 768 × 768 "
                "is the bottleneck, not the optimiser. The build record's faster rates (1e-4 and 2e-4 for eight epochs) "
                "reached the same plateau (test CER 0.798 and 0.807). The sibling GOT-OCR 2.0 row reached 0.759 on the same "
                "split with the same design; the two models are compared in the card, not here.</details>\n\n"
                "## 8. Held-out evaluation\n\n"
                "The test lines were never used for training or epoch selection, and no test image appears in the training or "
                "validation splits — but, as Section 4 explained, lines of the same page and hand can, so this is a "
                "same-collection estimate. The adapted model is scored exactly as the frozen model was in Section 6 and the "
                "four systems are put side by side. Read it in this order: **CER** first (the measure the epoch was selected "
                "on), then **WER** (whether whole words are read), then the hypothesis length (`hyp_chars` against "
                "`ref_chars`), then the exact-match rate. The cell then repeats the frozen and adapted rates on the test lines "
                "whose transcript does **not** occur in training, so you can see whether the repeated formulaic lines carry "
                "the result. `adapted_beats_frozen` and `adapted_beats_both_baselines` record the outcome; a result where the "
                "adapted model does not beat the frozen one (possible on your own data, for example printed text the frozen "
                "model already reads) is reported in the evaluation report and the run continues to the export — it is a "
                "finding, not an error. A **run history** keeps one row per pass through this cell, so an experiment can be "
                "compared with the default run (Section 10). One hundred and forty lines from one seeded split give **no "
                "dispersion estimate**, and the run-to-run spread of Section 7 applies here too; the deltas are sample-sanity "
                "evidence that the adaptation contract works, not a benchmark, and a result on one French council's minutes "
                "says nothing about other hands, other languages or other scripts until you measure them.\n\n"
                "**Predict before running:** if the CER falls, will the WER fall with it? Will any of the 140 lines be read "
                "exactly?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records, max_new_tokens=LINE_MAX_NEW_TOKENS, num_beams=NUM_BEAMS, batch_size=EVAL_BATCH_SIZE)\n"
                "adapted_val = pipe.evaluate(val_records, max_new_tokens=LINE_MAX_NEW_TOKENS, num_beams=NUM_BEAMS, batch_size=EVAL_BATCH_SIZE)\n"
                "comparison = {{metric: {{'empty': round(baseline_empty[metric], 3), 'constant': round(baseline_constant[metric], 3), 'frozen': round(frozen_test[metric], 3), 'adapted': round(adapted_test[metric], 3)}} for metric in METRICS}}\n"
                "comparison['delta_vs_frozen'] = {{metric: round(adapted_test[metric] - frozen_test[metric], 3) for metric in METRICS}}\n"
                "comparison['hypothesis_length'] = {{'ref_chars': adapted_test['ref_chars'], 'frozen_hyp_chars': frozen_test['hyp_chars'], 'adapted_hyp_chars': adapted_test['hyp_chars'], 'frozen_truncated': frozen_test['truncated'], 'adapted_truncated': adapted_test['truncated']}}\n"
                "for key, row in comparison.items():\n"
                "    print({{key: row}})\n\n"
                "# FL-M3: the same rates without the test lines whose transcript also occurs in training (Section 4).\n"
                "seen_ids = set(overlap['test'])\n"
                "unseen = [i for i, r in enumerate(test_records) if r['id'] not in seen_ids]\n"
                "transcript_breakdown = {{'all_test_lines': len(test_records), 'transcript_also_in_train': len(seen_ids), 'transcript_unseen': len(unseen)}}\n"
                "if unseen and seen_ids:\n"
                "    unseen_records = [test_records[i] for i in unseen]\n"
                "    for label, run in (('frozen', frozen_test), ('adapted', adapted_test)):\n"
                "        rates = ocr_metrics([run['hypotheses'][i] for i in unseen], unseen_records)\n"
                "        transcript_breakdown[label + '_unseen_transcripts'] = {{'cer': round(rates['cer'], 3), 'wer': round(rates['wer'], 3), 'n': rates['n']}}\n"
                "        transcript_breakdown[label + '_all'] = {{'cer': round(run['cer'], 3), 'wer': round(run['wer'], 3), 'n': run['n']}}\n"
                "print({{'transcript_breakdown': transcript_breakdown}})\n\n"
                "adapted_beats_frozen = adapted_test['cer'] < frozen_test['cer']\n"
                "adapted_beats_both_baselines = adapted_test['cer'] < min(baseline_empty['cer'], baseline_constant['cer'])\n"
                "if adapt_result['best_epoch'] == 0:\n"
                "    reading = 'The selector kept epoch 0, so the adapted model is the frozen model: no epoch beat it on validation.'\n"
                "elif not adapted_beats_frozen:\n"
                "    reading = 'The adapted CER is not below the frozen CER on the test lines: this adaptation did not help here. The export and reload below still run.'\n"
                "elif adapted_test['wer'] >= frozen_test['wer']:\n"
                "    reading = 'CER fell but WER did not: the gain is in characters inside words, and no more whole words are read than before.'\n"
                "else:\n"
                "    reading = 'CER and WER both fell: more characters and more whole words are read than by the frozen model.'\n"
                "print({{'adapted_beats_frozen': adapted_beats_frozen, 'adapted_beats_both_baselines': adapted_beats_both_baselines, 'best_epoch': adapt_result['best_epoch']}})\n"
                "print('Reading: ' + reading)\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data': 'BYOD' if USE_BYOD else 'sample', 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'best_epoch': adapt_result['best_epoch'], 'frozen_cer': round(frozen_test['cer'], 3), 'adapted_cer': round(adapted_test['cer'], 3), 'adapted_wer': round(adapted_test['wer'], 3)}})\n"
                "print(f\"{{'run':>3}} {{'data':>6}} {{'epochs':>6}} {{'lr':>8}} {{'best':>4}} {{'frozen':>7}} {{'adapted':>7}} {{'wer':>7}}\")\n"
                "for h in run_history:\n"
                "    print(f\"{{h['run']:>3}} {{h['data']:>6}} {{h['epochs']:>6}} {{h['learning_rate']:>8g}} {{h['best_epoch']:>4}} {{h['frozen_cer']:>7.3f}} {{h['adapted_cer']:>7.3f}} {{h['adapted_wer']:>7.3f}}\")\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'task': '<OCR>',\n"
                "    'data_source': data_source,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'split_unit': 'line image; no page or writer field, so lines of one page can be in training and test (same-collection estimate)',\n"
                "    'transcript_overlap': overlap,\n"
                "    'transcript_breakdown': transcript_breakdown,\n"
                "    'baselines': {{'empty': {{k: v for k, v in baseline_empty.items() if k != 'rows'}}, 'constant': {{k: v for k, v in baseline_constant.items() if k != 'rows'}}}},\n"
                "    'frozen_test': {{k: v for k, v in frozen_test.items() if k != 'rows'}},\n"
                "    'validation_metrics': {{k: v for k, v in adapted_val.items() if k != 'rows'}},\n"
                "    'test_metrics': {{k: v for k, v in adapted_test.items() if k != 'rows'}},\n"
                "    'per_line': [{{**frozen_row, 'frozen_hypothesis': frozen_hyp, 'adapted_cer': adapted_row['cer'], 'adapted_hypothesis': adapted_hyp}} for frozen_row, frozen_hyp, adapted_row, adapted_hyp in zip(frozen_test['rows'], frozen_test['hypotheses'], adapted_test['rows'], adapted_test['hypotheses'], strict=True)],\n"
                "    'comparison': comparison,\n"
                "    'adapted_beats_frozen': adapted_beats_frozen,\n"
                "    'adapted_beats_both_baselines': adapted_beats_both_baselines,\n"
                "    'reading': reading,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the delta row, the hypothesis length, the transcript breakdown, the printed reading and "
                "the run history.\n\n"
                "<details><summary>Check your reasoning</summary>No, and no. In the recorded T4 run the CER fell 0.992 → "
                "**0.797**, past both baselines — one fifth of the characters right — while the WER went 1.002 → 1.012: it did "
                "not fall, so the character gain sits inside words and no whole word is read. The hypotheses grew from 0.04 "
                "to 0.58 times the reference length (the adapted model writes something for every line, but not enough of it), "
                "and 0 of the 140 lines were read exactly. The transcript breakdown from that run's per-line hypotheses: on the "
                "135 test lines whose transcript does not occur in training the adapted CER is also **0.797** (frozen 0.992); "
                "the 5 repeated lines (84 characters) scored 0.821, so the verbatim repeats do not carry the result. What the "
                "breakdown cannot remove is the shared pages and hands (Section 4).</details>\n\n"
                "## 9. Look at the lines, re-run the three capabilities, export the adapter and reload it\n\n"
                "Six held-out lines are written as panels (`outputs/{stem}_examples/`: the line image with the reference, the "
                "frozen transcript and the adapted transcript beneath it) so the numbers can be checked by eye — compare the "
                "adapted rows with the references, not only with the empty frozen rows. The drawing from Section 5 is then "
                "run again through all three capabilities by the adapted model — the decoder that was tuned serves every task "
                "token, so this is a small look at what the adaptation did *outside* its task and its corpus (one drawing of "
                "evidence, not a measurement).\n\n"
                "`pipe.save_artifact` writes the trained tensors — the four decoder layers and the embedding norm, 106 tensors "
                "and about 269 MB in float32 — as `adapter.safetensors`, with a `manifest.json` recording the artifact format, "
                "the base model id and revision, the digest of the base `model.safetensors`, the tensor names, the file size "
                "and SHA-256, the task, the training configuration and the epoch history (OUT8). An **adapter** is only the "
                "changed tensors; it is meaningless without the pinned base. `Florence2Pipeline.from_artifact` re-verifies the "
                "base snapshot, checks the artifact manifest, its digest and its exact tensor set **before** deserialising, "
                "refuses any tensor outside the last four decoder layers and the embedding norm, and overlays the tensors onto "
                "a freshly loaded base — a new object from files, not the in-memory model (VER2). The cell checks for identical "
                "transcripts on eight test lines (**reload parity**, VER4) and stops with an explanation if they differ. Under "
                "BYOD `result.json` records your upload in place of the Belfort corpus block.\n\n"
                "**Predict before running:** after tuning the decoder on handwriting, will the drawing's caption, its box and "
                "its OCR stay the same? Will reload parity hold?"
            ),
            "code": (
                "import shutil\n\n"
                "examples_dir = Path('outputs/{stem}_examples')\n"
                "shutil.rmtree(examples_dir, ignore_errors=True)\n"
                "examples_dir.mkdir(parents=True)\n"
                "caption_font = ImageFont.load_default(size=18)\n"
                "for record, frozen_hyp, adapted_hyp in zip(test_records[:6], frozen_test['hypotheses'][:6], adapted_test['hypotheses'][:6], strict=True):\n"
                "    line = record['image']\n"
                "    width = min(1400, line.width)\n"
                "    line = line.resize((width, max(1, round(line.height * width / record['image'].width))))\n"
                "    sheet = Image.new('RGB', (max(width, 1400), line.height + 96), (255, 255, 255))\n"
                "    sheet.paste(line, (0, 0))\n"
                "    marker = ImageDraw.Draw(sheet)\n"
                "    for i, (tag, text) in enumerate((('REF', record['text']), ('FROZEN', frozen_hyp), ('ADAPTED', adapted_hyp))):\n"
                "        marker.text((8, line.height + 6 + i * 28), f'{{tag}}: {{text[:140]}}', fill=(20, 20, 20) if tag != 'FROZEN' else (150, 40, 40), font=caption_font)\n"
                "    sheet.save(examples_dir / f\"{{record['id']}}.png\")\n"
                "print({{'examples': sorted(p.name for p in examples_dir.iterdir()), 'rows': ['reference', 'frozen transcript', 'adapted transcript']}})\n\n"
                "adapted_results, adapted_timings, adapted_checks, adapted_report = run_capabilities(pipe, 'adapted')\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...', 'task': artifact_manifest['adapter']['task'], 'best_epoch': artifact_manifest['adapter']['best_epoch']}})\n\n"
                "reloaded = Florence2Pipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "before = [item['text'] for item in pipe.transcribe([r['image'] for r in test_records[:8]], max_new_tokens=LINE_MAX_NEW_TOKENS, num_beams=NUM_BEAMS)]\n"
                "after = [item['text'] for item in reloaded.transcribe([r['image'] for r in test_records[:8]], max_new_tokens=LINE_MAX_NEW_TOKENS, num_beams=NUM_BEAMS)]\n"
                "parity = {{'identical_lines': sum(a == b for a, b in zip(before, after, strict=True)), 'of': len(before)}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "reloaded = None  # free the second copy of the model before any re-run\n"
                "gc.collect()\n"
                "if parity['identical_lines'] != parity['of']:\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the model that was evaluated in Section 8. Re-run from Section 7 (it reloads the pretrained model before adapting), or restart the session and choose Run all.')\n\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'total_bytes': snapshot.get('total_bytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHTS_FILE, 'weight_format': 'safetensors, digest-verified', 'weight_sha256': pipe.weight_sha256}},\n"
                "    'data_source': data_source,\n"
                "    'corpus': None if USE_BYOD else {{'name': CORPUS_NAME, 'repo': CORPUS_REPO, 'revision': CORPUS_REVISION, 'file': CORPUS_FILE, 'license': CORPUS_LICENSE, 'language': CORPUS_LANGUAGE, 'row_groups': sorted(ROW_GROUP_PINS), 'shard_bytes': CORPUS_BYTES}},\n"
                "    'byod': byod,\n"
                "    'split_unit': 'line image (no page or writer field)',\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'drawing': {{'name': drawing_name, 'sha256': drawing_sha256, 'ocr_reference': drawing_reference, 'drawn_square': drawn_square}}, 'tasks_exposed': list(TASKS), 'frozen': {{'capabilities': {{task: {{'result': r['result'], 'generated_text': r['generated_text'], 'generation': r['generation'], 'text_input': CAPABILITIES[task].get('text_input'), 'seconds': frozen_timings[task]}} for task, r in frozen_results.items()}}, 'checks': frozen_checks, 'report': frozen_report}}, 'adapted': {{'capabilities': {{task: {{'result': r['result'], 'generated_text': r['generated_text'], 'generation': r['generation'], 'text_input': CAPABILITIES[task].get('text_input'), 'seconds': adapted_timings[task]}} for task, r in adapted_results.items()}}, 'checks': adapted_checks, 'report': adapted_report}}, 'output_files': ['outputs/{stem}_preview_frozen.png', 'outputs/{stem}_preview_adapted.png']}},\n"
                "    'comparison': comparison,\n"
                "    'transcript_breakdown': transcript_breakdown,\n"
                "    'adapted_beats_frozen': adapted_beats_frozen,\n"
                "    'adapted_beats_both_baselines': adapted_beats_both_baselines,\n"
                "    'reading': reading,\n"
                "    'adaptation': {{'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'learning_rate': LEARNING_RATE, 'epochs': EPOCHS, 'batch_size': BATCH_SIZE, 'seed': adapt_result['seed']}},\n"
                "    'examples': 'outputs/{stem}_examples',\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors'])}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'pillow': PIL.__version__, 'device': pipe.device, 'source': pipe.source, 'dtype': pipe.dtype}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "**What to notice:** the panels (references against adapted transcripts), what changed in the drawing's caption, "
        "box and OCR, the artifact's tensor count and size, and the reload-parity line.\n\n"
        "<details><summary>Check your reasoning</summary>Partly, and yes. In the recorded T4 run the caption changed from "
        "`a red and blue circle with the word dimer 2026 on it` to `Dim 2026 logo with a red and blue circle.`, the single "
        "`poster` box covering the drawing stayed, and the OCR still read `DIMER 2026` exactly (CER 0.000) — tuning the "
        "shared decoder on handwriting touched the caption task it was never trained on, which is one drawing of evidence, "
        "not a measurement. The artifact held 106 tensors (4 decoder layers × 26 plus the 2 tensors of the embedding layer "
        "norm), 268,769,008 bytes, and reload parity was 8/8: the exported adapter is the model that was evaluated. Parity "
        "holds because the adaptation started from the pretrained base, so the adapter carries every tensor that differs "
        "from it.</details>\n\n"
        "## 10. Your turn — change one thing: a higher learning rate\n\n"
        "Optional; **Predict → Change one thing → Run → Observe → Explain**. It retrains, so it takes about as long as "
        "Sections 7–9 did (Section 7 alone took 822 s on the T4 record).\n\n"
        "1. **Predict:** with `LEARNING_RATE = 1e-4` (twice the default), will the validation CER fall faster in the first "
        "epochs, will it end lower than the default run's plateau near 0.80, and will the training loss end lower? Write your "
        "guesses next to the default run's row in the Section 8 run history.\n"
        "2. **Change:** in Section 7 set `LEARNING_RATE = 1e-4`. Change nothing else.\n"
        "3. **Run:** select the Section 7 cell and choose **Runtime → Run after**. Section 7 reloads the pretrained model "
        "before adapting, Section 8 compares against the same Section 6 frozen score and adds a row to the run history, and "
        "Section 9 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 7, epoch 0 shows the *frozen* validation CER again (0.969 in the recorded run), not the "
        "adapted one — the sign that the model was reset; read how the loss and the validation CER move. In Section 8, compare "
        "the two rows of the run history and the reading line.\n"
        "5. **Explain:** in one or two sentences, did doubling the learning rate move the held-out CER, and is the "
        "difference between the two runs larger than the run-to-run spread and what 140 lines can resolve?\n\n"
        "<details><summary>Check your reasoning</summary>The build record ran this rate for eight epochs (not six) and "
        "reached a test CER of 0.798 — the same plateau as the default's 0.797 — and 2e-4 reached 0.807. Expect the "
        "training loss to fall faster and the validation CER to reach the plateau sooner, and then stop. That is the point "
        "of the activity: when every rate tried lands on the same plateau, the limit is what the frozen encoder passes to "
        "the decoder, not how fast the decoder learns. Your six-epoch numbers are your own result; a difference of a few "
        "thousandths between the two rows is not evidence that one rate is better.</details>\n\n"
        "## Interpretation and limits\n\n"
        "A prompt-driven document model reads the print it was trained on, and nineteenth-century cursive French is not among "
        "it: the frozen `<OCR>` scores a character error rate of 0.992 on the Belfort lines — silence, a dash or "
        "nothing for almost every line. A bounded fine-tuning of the last four decoder layers on 600 transcribed lines moves it "
        "off the floor but not far (0.797 CER and 1.012 WER in the build record, 0 of "
        "the held-out lines exact; the constant-transcript baseline scores 0.944) and the validation curve plateaus there at "
        "every rate tried, with a 269 MB adapter that reloads line-for-line. That is the claim: the adaptation contract "
        "works end to end on one task of a multi-task model with a real labelled set, and the numbers it produces are read as "
        "micro and macro rates, against two non-adapted baselines and the frozen model, with the hypothesis length beside "
        "them rather than in isolation — and they say that a decoder-only adapter cannot make this encoder read cursive. "
        "The obvious next experiment, adapting the BART encoder's last layers too (or the vision tower), is not in this "
        "repository.\n\n"
        "The test split is 140 lines from one seeded draw of one 800-line sample, the validation split that picks the epoch is "
        "60, and both rates are corpus edit distances over one crowdsourced transcription — not a benchmark, not a measure of "
        "reading order or layout. **The split is by line image, not by page:** the dataset has no page or writer field, so "
        "the held-out lines can share pages and hands with the training lines, and the held-out rate is a same-collection "
        "estimate that is likely optimistic for a new register or a new hand (the verbatim-repeated transcripts, which "
        "Section 8 removes, do not change it). So a gain here says the contract works on one council's minutes, not that the "
        "adapted model handles other hands, other languages, other scripts or your scans. The decoder that was tuned serves "
        "every task token: the drawing re-run in Section 9 is one image of evidence about what the tuning did to `<CAPTION>` "
        "and `<OD>`, not a measurement, and a deployment that needs the other tasks must measure them after adapting. The "
        "decoder was adapted, not the vision tower: what the encoder cannot resolve in a 128-px line squashed into a 768 × "
        "768 square stays unread.\n\n"
        "Three things to carry to real data. **Baselines first:** the empty and constant-transcript rates on *your* transcripts, "
        "and the frozen model's hypothesis length, are the numbers to read before any adapted one. **Rates above 1.0:** an "
        "uncapped CER tells you the model is generating, not reading; a capped one would hide it. **Leakage:** keep every image "
        "in one split (the contract de-duplicates by decoded pixels), and when your data records the page, writer or volume "
        "of each line, split by that — lines cut from the same page share a hand, and this notebook's split cannot keep them "
        "together because its dataset does not say which page a line came from.\n\n"
        "Successful execution proves that the recorded repository revision's package, carried in this standalone notebook, can "
        "acquire and digest-verify the pinned model snapshot, fetch and digest-verify a real labelled line set, validate the "
        "demonstrated dataset contract with no image in two splits, execute the inference contract for three task tokens and "
        "a bounded fine-tuning of one of them with the model's own objective, evaluate against two non-adapted baselines and "
        "the frozen model on a held-out split of line images, and emit the shown machine-readable artifacts — without the "
        "repository being reachable. It does **not** establish benchmark superiority, recognition quality on any other hand, "
        "language or document family, caption or detection quality after adaptation, or production fitness.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one thing; note the numbers you "
        "want to compare first (the Section 8 run history keeps one row per pass). In Colab, **Runtime → Run after** runs "
        "the selected cell and every cell below it; Sections 5, 6 and 7 reload the pretrained model before they use it, so no "
        "experiment inherits an earlier adaptation.\n\n"
        "- **A higher learning rate:** Section 10.\n"
        "- **More epochs:** set `EPOCHS = 10` in Section 7, select Section 7 and choose **Run after**. Does the validation "
        "CER keep falling after epoch 6, and which epoch does the selector keep?\n"
        "- **Greedy decoding:** in Section 6 add the line `NUM_BEAMS = 1` under `LINE_MAX_NEW_TOKENS`, select Section 6 and "
        "choose **Run after**. What does giving up beam search cost the frozen and the adapted CER? (Restart and **Run all** "
        "to return to 3 beams.)\n"
        "- **A smaller token budget:** set `LINE_MAX_NEW_TOKENS = 64` in Section 6, select Section 6 and choose **Run "
        "after**. How does the `truncated` count change, and what does it do to the CER?\n"
        "- **Phrase grounding:** in Section 5 add the entry `'<CAPTION_TO_PHRASE_GROUNDING>': {{'input': 'image + text', "
        "'output': 'boxes for the phrase', 'max_new_tokens': DEFAULT_MAX_NEW_TOKENS, 'text_input': 'a red square'}}` to "
        "`CAPABILITIES`, select Section 5 and choose **Run after**. Where does the box for the phrase land, and does the "
        "adapted model in Section 9 still find it? (`run_capabilities` passes each entry's `text_input`, and `result.json` "
        "records it.)\n"
        "- **Another split:** change `SPLIT_SEED` in Section 4, select Section 4 and choose **Run after**. How far do the "
        "frozen and adapted CER move with a different draw of 140 test lines — more or less than the default run's delta?\n"
        "- **Your own lines:** BYOD (Section 4, then **Run after**). Before the adapted number, how do the two baselines "
        "and the frozen model score on your transcripts?\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux wheels. "
        "Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **The run is very slow, or the session ends before Section 9.** On CPU the default path takes hours "
        "(Prerequisites). Switch to a GPU runtime (**Runtime → Change runtime type**) and choose **Run all** again.\n"
        "- **\"The isolated environment's Python process exited\".** Usually the runtime ran out of memory (the model is "
        "about 3.1 GB in float32, and Section 9 briefly holds two copies). Restart the session and choose **Run all**. A "
        "CUDA out-of-memory error in Section 7 can be avoided with `BATCH_SIZE = 4`.\n"
        "- **`FileNotFoundError: snapshot file missing` or a `sha256`/`size` `ValueError` in Section 3.** A staged file is "
        "incomplete or altered — delete it from `weights/florence-2-large-community/` and run Section 3 again. A row-group "
        "digest mismatch in Section 4 is the same for the corpus cache under `weights/belfort/`.\n"
        "- **`RuntimeError: checkpoint does not match the native Florence-2 architecture` in Section 3.** The staged weights "
        "are not the pinned converted checkpoint — re-stage.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: a split with too few lines (at least 12 distinct "
        "images in all), two files with one name, a missing `transcripts.csv`, an image without a row or a row without an "
        "image, a transcript over 512 characters, or a duplicate id. Fix the zip and run Section 4 with **Run after** "
        "again. An empty or cancelled upload, or a runtime without the Colab upload dialog, asks you to choose a file or set "
        "`BYOD_PATH`.\n"
        "- **Section 8 reads \"did not help\" or \"The selector kept epoch 0\".** Not an error: under these settings the "
        "adaptation did not beat the frozen model. Read the epoch history in Section 7; the export and reload in Section 9 "
        "still run.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated model. Re-run from "
        "Section 7 (it reloads the pretrained model first), or restart the session and choose **Run all**.\n"
        "- **Numbers differ slightly from the recorded run.** GPU models and library builds differ, and because decoding is "
        "autoregressive one different token changes the rest of a line; differences in the second or third decimal are "
        "expected. Larger differences on the default settings mean a form field was changed.\n"
        "- **A \"slow image processor\" notice** from `transformers` is expected and harmless.\n"
        "- **You re-ran the routing cell in Section 1.** It starts a new isolated process and discards every variable "
        "created so far; choose **Run all** again.\n\n"
        "## Glossary\n\n"
        "- **Task prompt token:** the token such as `<OCR>` or `<CAPTION>` that selects what Florence-2 generates.\n"
        "- **DaViT / BART:** the vision tower that turns the image into 577 visual tokens, and the encoder–decoder language "
        "model that reads them with the prompt and generates text.\n"
        "- **Beam search:** decoding that keeps the `num_beams` most likely partial outputs at each step and returns the "
        "best; deterministic for fixed weights, device and dtype. Greedy decoding is one beam.\n"
        "- **Levenshtein distance:** the minimum number of character (or word) insertions, deletions and substitutions that "
        "turn one string into another.\n"
        "- **CER / WER (micro):** total character (word) edits over total reference characters (words) across the split; "
        "**macro** is the mean of the per-line rates. Not capped at 1.0.\n"
        "- **Empty / constant-transcript baseline:** systems that never look at the image — predicting nothing, or one "
        "training transcript (the **medoid**, the line closest on average to the others) for every line.\n"
        "- **Teacher forcing:** during training the decoder is fed the correct previous tokens of the transcript, not its own "
        "predictions.\n"
        "- **Frozen encoder cache:** the encoder output for each training line, computed once without gradients and reused "
        "every epoch because nothing before the decoder is trained.\n"
        "- **Epoch / validation selection:** one pass over the training lines; the epoch kept is the one with the lowest "
        "validation CER (epoch 0 = the frozen model).\n"
        "- **Training / validation / test split:** lines used to train, to choose the epoch, and to report the final result "
        "once; split by line image, so no image is in two splits — but not by page (Section 4).\n"
        "- **Same-collection estimate:** a held-out score on data drawn from the same pages, hands and registers as the "
        "training data; usually optimistic for new sources.\n"
        "- **safetensors / adapter / reload parity:** a tensor file format that cannot run code when loaded; the saved "
        "trained tensors; and the check that a pipeline rebuilt from them and the pinned base gives the same transcripts.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- The task: from ___ to ___. On the test lines the empty baseline scored CER ___, the constant transcript ___, the "
        "pretrained model ___ and the adapted model ___ (kept epoch ___).\n"
        "- WER moved from ___ to ___, so the change in CER reflects ___ (characters inside words / whole words).\n"
        "- Without the test lines whose transcript is also in training, the adapted CER was ___; the split cannot rule out "
        "___ because ___.\n"
        "- One failure mode I saw in the panels: ___. On the drawing, the adaptation changed ___.\n"
        "- A higher learning rate (Section 10) changed ___; the difference between the runs is / is not larger than one "
        "seeded split can resolve, because ___.\n"
        "- Before trusting this adaptation on my own documents I would measure ___ on ___, split by ___, with the baselines "
        "first.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/florence2-vision-language-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/florence2-vision-language-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance and pin history: https://github.com/kurtvalcorza/florence2-vision-language-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Pinned converted checkpoint: https://huggingface.co/{MODEL_ID}\n"
        "- Original weights and licence: https://huggingface.co/microsoft/Florence-2-large\n"
        "- Florence-2 paper (Xiao et al., 2023): https://arxiv.org/abs/2311.06242\n"
        "- Transformers Florence-2 documentation: https://huggingface.co/docs/transformers/model_doc/florence2\n"
        "- Belfort-line dataset (Teklia, MIT): https://huggingface.co/datasets/Teklia/Belfort-line — Tarride et al., Handwritten Text Recognition from Crowdsourced Annotations (HIP 2023): https://doi.org/10.1145/3604951.3605517\n"
        "- Sibling row on the same split: https://github.com/kurtvalcorza/got-ocr2-pipeline\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
